# Generated by Django 4.2.13 on 2024-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpayment',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectpurchases',
            old_name='desription',
            new_name='description',
        ),
    ]
