# Generated by Django 4.2.13 on 2024-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, default='on_progress', max_length=100, null=True),
        ),
    ]
