# Generated by Django 4.2.13 on 2024-11-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_desription_projectpayment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='homeAdress',
            new_name='homeAddress',
        ),
        migrations.RenameField(
            model_name='projectbudget',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectdirectcost',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectexpense',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectinvoice',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectupdate',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='purchasesaccumulated',
            old_name='desription',
            new_name='description',
        ),
    ]
