# Generated by Django 4.2.13 on 2024-08-29 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assignmentupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(blank=True, max_length=10000, null=True)),
                ('leave_reason', models.CharField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(blank=True, max_length=10000, null=True)),
                ('action', models.CharField(blank=True, max_length=10000, null=True)),
                ('action_reason', models.CharField(blank=True, max_length=10000, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
