# Generated by Django 4.2.13 on 2024-11-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_homeadress_customuser_homeaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdateSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectUpdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectupdate')),
            ],
        ),
    ]
