# Generated by Django 4.2.13 on 2024-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projectupdatesubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
