# Generated by Django 4.2.13 on 2024-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='action',
            field=models.CharField(default='pending', max_length=10000),
        ),
    ]
