# Generated by Django 4.2.13 on 2024-08-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leaves_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='status',
        ),
    ]
