# Generated by Django 4.2.13 on 2024-11-28 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_projectupdatesubtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdatesubtask',
            name='assigner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_assigner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectupdatesubtask',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
