# Generated by Django 4.2.13 on 2024-08-29 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_leaves_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
