# Generated by Django 4.2.13 on 2024-08-30 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_leaves_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
